### ISSUE TITLE
[Specific DID Method Schemes] Very, very confuding non-recommendation for central registries needs to be removed

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#133]
In https://w3c-ccg.github.io/did-spec/#specific-did-method-schemes, it states:

>Since DIDs are intended for decentralized identity infrastructure, it is NOT RECOMMENDED to establish a registry of unique DID method names. Rather the uniqueness of DID method names should be established via human consensus, i.e., a specific DID scheme MUST use a method name that is unique among all DID method names known to the specification authors at the time of publication.

...and then in the next paragraph, directs the reader to an Appendix listing specific centralized registries...

> A list of known DID method names and their associated specifications is provided in Appendix A. Registries

Question 1.  This is confuding to the reader, why these sentences been left in the draft spec?

Question 2. What is the process for disambiguating/ensuring uniqueness of DID method names?

**Comment by TomCJones** [comment]
agree with @mwherman2000  on this

**Comment by mwherman2000** [comment]
In support of my opening comment, Registeries is also a formal W3C CCG work item category: https://github.com/w3c-ccg/community/blob/master/work_items.md#registries ...and within that, the DID Methods Registry is a specific work item.

**Comment by mwherman2000** [comment]
https://github.com/w3c-ccg/did-spec/commit/a2178570794a86147a47d3323a726fac185f1e4d doesn't address the specific wording issue highlighted at the beginning of this issue. The change only moved the offending sentences to another part of the document. Please re-open this issue until it is resolved.

**Comment by rhiaro** [comment]
The sentence wasn't moved, but rephrased in place. The intention is to note that new DID methods go through a lightweight human-centered W3C process with a certain bar to entry (DID method should be spec'd) whilst recommending against any kind of software-driven first-come-first-served registry of method names, in order to prevent a landgrab for method names.

**Comment by mwherman2000** [comment]
Me bad.  My original questions 1 and 2 were a distraction from the core issue:  Why do we say:

>  it is NOT RECOMMENDED to establish a registry of unique DID method names.

and then in the next paragraph say:

> A list of known DID method names and their associated specifications is provided in Appendix A. Registries

Either there is a need or requirement for central registries or this isn't.  We need to remove the contradictory messages.

If by "it is NOT RECOMMENDED to establish a registry of unique DID method names", we really mean "it is NOT PREFERABLE OR DESIRABLE to establish a registry of unique DID method names" ...this is an editorial comment/viewpoint and should be removed.

**Comment by talltree** [comment]
On Sun, Mar 3, 2019 at 6:10 PM Michael Herman (Toronto) <
notifications@github.com> wrote:

> Me bad. My original questions 1 and 2 were a distraction from the core
> issue: Why do we say:
>
> it is NOT RECOMMENDED to establish a registry of unique DID method names.
>
> and then in the next paragraph say:
>
> A list of known DID method names and their associated specifications is
> provided in Appendix A. Registries
>
> Either there is a need or requirement for central registries or this
> isn't. We need to remove the contradictory messages.
>
> If by "it is NOT RECOMMENDED to establish a registry of unique DID method
> names", we really mean "it is NOT PREFERABLE OR DESIRABLE to establish a
> registry of unique DID method names" ...this is an editorial
> comment/viewpoint and should be removed.
>
Michael, it turns out that the question of "registry of unique DID method
names" is a *critically* important question to some implementers and some
governance authorities. This was already clear before the Rebooting the Web
of Trust conference that just ended in Barcelona, but there were several
very deep discussions about it there.

I would like to:

   1. Propose that we replace any/all text dealing with this subject in the
   current version of the spec with a new, short section entitled "Governance
   of DID Method Namespaces".
   2. Volunteer to draft the text explaining why this subject is out of
   scope for the spec.

How does that sound to you (or to anyone else on this thread)?

**Comment by mwherman2000** [comment]
1. Yes, that would address and close this issue.
2. Let's see that the new section reads like.

**Comment by talltree** [comment]
Agreed—the wording of the new section is critical. I plan to make a proposal shortly.

**Comment by peacekeeper** [comment]
Methods are now listed in the separate [DID Method Registry](https://w3c-ccg.github.io/did-method-registry/). And @rhiaro has done a great job with https://github.com/w3c-ccg/did-spec/pull/186 which has been merged. I think this issue can be closed. @mwherman2000 do you agree?

**Comment by rhiaro** [comment]
Closing because there has been no further comment regarding the changes made. If there are issues with the new sections [Unique Method Names](https://w3c-ccg.github.io/did-spec/#unique-did-method-names) and [Choosing DID resolvers](https://w3c-ccg.github.io/did-spec/#choosing-did-resolvers) please raise new issues, and if there are problems with copy in the [DID Method Registry](https://w3c-ccg.github.io/did-method-registry/) itself, please raise issues [over there](https://github.com/w3c-ccg/did-method-registry/issues/).
