### ISSUE TITLE
[Extensibility] references the formal concept of the Decentralized Identifiers Data Model but there is nothing in the document with this formal name/concept

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#151]
In https://w3c-ccg.github.io/did-spec/#extensibility, it references the formal concept of a `Decentralized Identifiers Data Model` for the first time.  

However, there is no previous mention of a formal Data Model in the draft DID spec.  There is no previous section or subsection with a heading of "Decentralized Identifiers Data Model" or simply "Data Model".

There is no picture/graphic of the DID Data Model.  

I believe the lack of a clearly defined and visual Data Model is the root cause of many of the Issues that have been documented recently.

Here's an example of a possible solution ...

[Hyperledger Indy/Sovrin Comprehensive Architecture Reference Model (INDY ARM) - latest version](https://hyperonomy.com/2019/01/13/hyperledger-indy-sovrin-comprehensive-architecture-reference-model-arm/) - bullets (12) thru (16) in both the diagram, Narration, and principles.

Also checkout https://hyperonomy.com/2019/01/04/the-path-from-a-id-did-to-a-real-life-something/

**Comment by mwherman2000** [comment]
There is an ad-hoc reference to "data model" in the subtitle of the document and couple references in the front-mater of the document but nothing that is called out as the DID Data Model.

**Comment by jandrieu** [comment]
This is a good point. Because valid DIDs *always* resolve to a DID Document, and NOT to any other type of resource, the DID spec specifies both the DID and the DID Document (which is what the data model is about).  DID methods and DID resolution should be external specs.  We should explain that sooner so it those distinctions are clear.  

There's a valid question about what content should be in a separate spec. For example, until recently, we had resolution-related text, which is now being moved to a dedicated DID Resolution specification. 

My perspective is that a DID that resolves to anything OTHER than a DID Document is not a valid DID, which makes the definition of the DID and DID Document intimately related.

I suppose it is still an open question where we should state the requirements for ALL methods. These probably go to DID Resolution, but its worth discussing.

**Comment by talltree** [comment]
Joe, the design from the start was that the main DID spec would include all
normative requirements (and also non-normative guidance) that applies to
ALL DID methods. In essence, it's the checklist/cookbook for a DID method
specification.

I could see some additional guidance about DID method development going
into the DID Resolution specification, but I strongly support all DID
method specification requirements going into the main DID spec.

**Comment by mwherman2000** [comment]
@rhiaro Why was this issue closed without the specific text being resolved in the draft DID spec?  Please re-open it.

**Comment by mwherman2000** [comment]
> valid DIDs _always_ resolve to a DID Document

This is not a true statement @jandrieu.  

DIDs can simply standalone without ever having to be resolved to a DID Document.  Here's an example from the `getting_started.py` Indy script:
https://github.com/w3c-ccg/did-spec/issues/151#issuecomment-459829632
This script uses DIDs hundreds of times and never once uses, references, to resolves a DID to a DID Document.

In addition, how an application chooses to use a DID is entirely up to that application.  For example, the same script above can use, with impunity, the same DIDs to store and index documents on IPFS or a plain old file system.

> im·pu·ni·ty: exemption from punishment or freedom from the injurious consequences of an action.

**Comment by rhiaro** [comment]
> @rhiaro Why was this issue closed without the specific text being resolved in the draft DID spec? Please re-open it.

As far as I can see, this issue has at no point been closed.

**Comment by mwherman2000** [comment]
> > @rhiaro Why was this issue closed without the specific text being resolved in the draft DID spec? Please re-open it.
> 
> As far as I can see, this issue has at no point been closed. Definitely valid, and I expect it will be addressed as part of the follow up to #159

My bad: Why was https://github.com/w3c-ccg/did-spec/issues/142 closed with no resolution?

**Comment by brentzundel** [comment]
My two cents:
A DID should always resolve to a DID document. The fact that Indy does not
do this means it does not comply with the spec. (Work is underway right now
to change this and bring DID documents to Indy).
Even pairwise DIDs that may never be anchored to a ledger should resolve to
a DID document.
A DID should not resolve to anything other than a DID document.
A DID is not just a decentralized identifier, it is a decentralized
identifier tied to a document that outlines the ways to prove control of
the identifier.

**Comment by mwherman2000** [comment]
> A DID is not just a decentralized identifier, it is a decentralized identifier tied to a document that outlines the ways to prove control of the identifier.

Maybe this is the difference between a DID and a Verifiable DID?

**Comment by brentzundel** [comment]
On Sat, Feb 2, 2019, 17:14 Michael Herman (Toronto) <
notifications@github.com> wrote:

> A DID is not just a decentralized identifier, it is a decentralized
> identifier tied to a document that outlines the ways to prove control of
> the identifier.
>
> Maybe this is the difference between a DID and a Verifiable DID?
>
If a DID isn't verifiable, isn't it just a GUID?

**Comment by mwherman2000** [comment]
That 'tis the question.  For example, I can create a DID in my wallet and then use it for several different use cases without: (a) ever persisting to a Ledger and (b) a requirement to create a DID Document.  Here's some code:
https://github.com/mwherman2000/indy-dev/blob/master/python/getting_started-verbose.py#L40-L55

**Comment by brentzundel** [comment]
I am familiar with that code, and would say that while it should certainly
be possible to use a DID without anchoring it to a ledger, creating one
without a corresponding DID document means it does not conform to the spec
(and therefore isn't really a DID).
That's why the indy codebase will be changing to add DID documents, even in
peer to peer scenarios.

**Comment by peacekeeper** [comment]
Note that the ledger or other target system where the DID is created/registered does not necessarily have to support DID documents natively, in order to conform to the spec. All that's required is to have a well-defined DID Resolution process that produces a DID document. Bitcoin- and Ethereum- based DID methods don't "store" a DID document anywhere, but a resolver can still produce one.

In the case of Indy/Sovrin, it will be nice to have native support for DID documents in that particular target system, but even without it, e.g. the [Universal Resolver](https://uniresolver.io/) can already resolve `did:sov` identifiers to DID documents today.

**Comment by mwherman2000** [comment]
> I am familiar with that code, and would say that while it should certainly
be possible to use a DID without anchoring it to a ledger, ...

@brentzundel If you re-read the code, it doesn't in fact anchor the DID to the Ledger ...it doesn't require a DID Document to accomplish this.  Here's a visualization of the first several tasks in the script...

![Government - Onboarding](https://raw.githubusercontent.com/mwherman2000/indy-dev/da28f23ee95b378d7f7b65de9e551fdbf6d7f712/python/doc/images/Indy-SDK-Getting-Started-1.1-MessageFlow.png) ...click to enlarge it.

**Comment by talltree** [comment]
I A DID is not just a GUID or UUID. Those things exist and we do not need
to reinvent them. A DID is specifically a *cryptographically-verifiable
identifier*. So there is no need to add the adjective "Verifiable" in front
of it.

If you have invented an identifier that is cryptographically self-verifying
without reference to any external metadata, it feels like an academic
argument to call that a DID. But if that metadata is in fact virtual, i.e.,
encoded in the identifier itself, then IMHO there still IS a "virtual" DID
document (one that could be rendered with the proper algorithm), and thus
it could still be a DID.

Michael, is that what you have in mind?

I've been thinking about it a long time (that's the benefit of 2+ years
working on the evolution of the DID spec), and IMHO the most essential
quality of a DID is that it is *an addressable abstraction over
a cryptographic key pair.* In other words, with the DID, you can
always  *get the cryptographic
key you need in your own context*.  For example, if you're the DID
controller, you can get to either the public (verification) or private
(signing) key. If you're not the DID controller, you can only get to the
public key. But you can still verify it.

It doesn't have to come from a public ledger or private ledger or any
ledger. You just have to be able to retrieve it—that's why the DID is an
abstraction on the key (pair).

Thus the publicKey property of a DID document.

The second most essential quality of a DID is that it is *an addressable
abstraction over a service endpoint*, i.e., a network location where you
can interact with some kind of service associated with the DID (in Indy we
call them agents, others call them hubs—choose your name). But not all uses
of a DID need a service endpoint.

Thus the service property of a DID document.

The third most essential quality of a DID is that it *provides a standard
means of authentication* of the DID controller.

Thus the authentication property of a DID document.

Hope this helps,

=D

**Comment by mwherman2000** [comment]
@talltree Your discussion starts off in a good general direction, then for me it diverges :-) ...I'll comment in detail later today.  In the meantime, my first reading of your comments (as well as the offline discussions about re-structuring the draft DID spec) inspired the following *DID 7-Layer Model*...

![DID 7-Layer Model](https://raw.githubusercontent.com/mwherman2000/indy-dev/master/images/DID-7-Layer-Model.png)

"_I'll be back..._"

**Comment by mwherman2000** [comment]
From @msporny (during the CCG call): https://w3c.github.io/vc-data-model/ is a good example.

**Comment by mwherman2000** [comment]
@talltree Replying to your comments [[above](https://github.com/w3c-ccg/did-spec/issues/151#issuecomment-460536939)], ...

We’re truly in the embryonic stages of giving birth to an exciting and powerful new technology/paradigm/platform.  Nobody really understands what it is going to produce and the profound changes it is going to have – and here, I will use your analogy, like the birth of DNS. It's not a time to be _exclusionary_ ...it's a time to be inclusionary.

What I am asking for is for Level 2 and Level 3 to be recognized because they also have potential for use cases we can’t imagine …perhaps lightweight use cases in the IoT space, process control, other embedded systems, etc. where it isn’t easy or practical to support the heavy(ier) weight of the Levels 4-6 layers and protocols. 

...from an Indy perspective, recognizing Level 2 and Level 3 doesn’t require any new code to be written or existing code to be changed.  Levels 2 and Level 3 have already been implemented and are functioning well.

If you watch @peacekeeper 's DID Resolution webcast starting 400 seconds into the video, Markus does a good job of explaining how a DID Document is reconstructed (aka resolved) from NYM and ATTRIB transactions on the Ledger: https://www.youtube.com/watch?v=gf2g4O3yqCc&feature=youtu.be&t=400 …watch for 3 minutes from 6:40 to timecode 9:30.

Level 3 is saying: if you have a NYM Transaction (or equivalent), you have a Verifiable DID …with no DID Document.  …because a NYM Tx, by itself, is like the degenerate/simplest case of a DID Document.

**Comment by talltree** [comment]
Michael, just to clarify, DID documents have always been able to be
"virtual", i.e., composed of metadata retrieved by a DID method from
wherever the DID method needs to get it. An actual DID document in a
specific serialization does not need to be stored anywhere. That's all up
to the DID method.

That's why all DIDs are verifiable, and why it strikes me as misleading to
talk about a "DID stack" (vs. an SSI stack, of which DIDs
registration/resolution is just the first layer). With DIDs, there's just:

   1. The DID—a string conforming a particular syntax defined by the DID
   spec (generic) and DID method spec (specific);
   2. The DID method, which defines how a resolver will resolve the DID
   into what *eventually* will be a conformant DID document (at the *end* of
   the resolution process), and
   3. The final result of the DID resolution process, which is a conformant
   DID document (again, the richness of which depends on the capabilities of
   the DID method).

Those three areas are what the DID spec needs to define the rules for (plus
security and privacy considerations, which are considerable).

=D

**Comment by mwherman2000** [comment]
[Humorous sidenote: @talltree I think we're dreaming the same dream at the same time (modulo time zones) :-)]

I agree with for the lower layers but want to postulate: Where should DID Documents be defined/spec'ed out? ...given that they are solely an output of the DID Resolution process?

Digging deeper... is there an analogy/are there parallels between:
- the DID and DID Document "information architecture", and 
- the IP Address/TCP-IP/DNS information architecture?

Is the IP Address/TCP/IP information architecture analogous to DIDs?
...similar to the way DID Documents are to DNS entries?

Reference: Here's a DNS primer that some people might find helpful (DNS is much more than a `domain name` => `IP address` resolver):
https://hyperonomy.com/2019/01/02/dns-domain-name-service-a-detailed-high-level-overview/

**Comment by mwherman2000** [comment]
Here's an updated version of the DID 6-Layer Model to illustrate the points in the preceding comment...

![image](https://user-images.githubusercontent.com/6101736/52414647-20827580-2aa2-11e9-82a2-ad8fc2075ac4.png)

**Comment by talltree** [comment]
Michael, sorry to be slow but I was in a DKMS workshop all day today.

When I looked at the two columns on the right of your diagram—in other
words, when I realized what you *meant* by your six-layer diagram on the
left—all I heard was beautiful music.

(And now I know what you meant by, "dreaming the same dream" ;-)

=Drummond

**Comment by rhiaro** [comment]
There is now (https://github.com/w3c-ccg/did-spec/commit/0366ed045779910623e6930f66a799cfcc184562) a Core Data Model section in the spec. It's just a stub, and the precise contents will be ironed out and it will be filled out with an overview of the main concepts, so hopefully that resolves this issue.

**Comment by mwherman2000** [comment]
In the proposed changes https://github.com/w3c-ccg/did-spec/commit/0366ed045779910623e6930f66a799cfcc184562, I don't see where the phrase "Decentralized Identifiers Data Model" was removed or changed.

We should make sure Core Data Model is used consistently through the document (including the title).
