### ISSUE TITLE
[Overall Scope] What is considered Normative (and in-scope), Informative (and in-scope) and just plain out of scope?

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#158]
In terms of the scope of the draft DID spec, what is considered Normative (and in-scope), Informative (and in-scope) and just plain out of scope?

This is closely related to issue https://github.com/w3c-ccg/did-spec/issues/157 but different.  It's is also related to issue https://github.com/w3c-ccg/did-spec/issues/138.

I propose the following green highlight regions of the INDY ARM be considered Normative topics (and in-scope); yellow regions encompass Informative (Not Normative) topics ...and may or may not be considered in-scope.

![image](https://user-images.githubusercontent.com/6101736/51430474-1ffc6a80-1bd9-11e9-92e0-f9381c713e8c.png)

INDY ARM Reference: [Hyperledger Indy/Sovrin Comprehensive Architecture Reference Model (INDY ARM) - latest version](https://hyperonomy.com/2019/01/13/hyperledger-indy-sovrin-comprehensive-architecture-reference-model-arm/)

**Comment by TomCJones** [comment]
IMHO it is a duplicate of 138

**Comment by mwherman2000** [comment]
Closed as a duplicate of #138.

**Comment by talltree** [comment]
I very very strongly oppose any suggestion that a DID is not verifiable. The very definition of a DID includes (but is not limited to) that it is a **cryptographically verifiable identifier**. Full stop.

That does not mean that there cannot be multiple ways of associating a DID with its key material in order to do that verification. But that does not (and should not) take a seven-layer model.
