### ISSUE TITLE
[Abstract] Rewording...

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#214]
Change...

> Service endpoints enable trusted interactions with the DID controller.

to 

> Service endpoints enable trusted interactions with a DID controller.

**Comment by rhiaro** [comment]
Following the alignment with DID WG Charter language, this now reads "Service endpoints enable trusted interactions with the DID subject." but the original grammatical point may still stand. Although I think "the" is correct because it implies specifically the subject associated with the service endpoints.

**Comment by jandrieu** [comment]
Spec was re-worded to match the charter, and an ad-hoc check for consensus supports the current language. If this is still a concern, please raise an issue in the DID WG did-spec repo. https://github.com/w3c/did-spec
