### ISSUE TITLE
[Introduction] Rewording...

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#219]
Change...

> Because DIDs reside on a distributed ledger, each entity may serve as its own root authority—an architecture referred to as DPKI (decentralized PKI).

to

> Because DIDs are assumed to reside on a distributed ledger, each entity may serve as its own root authority—an architecture referred to as DPKI (decentralized PKI).

This is important because DIDs, the actual identifier, can reside anywhere: in a signature, in  a text file, in a SQL database, a file on IPFS.

**Comment by peacekeeper** [comment]
@mwherman2000 in cases like this, could you open a PR with the propose change, instead of creating an issue? That way we can track it better and simply merge it. Same for https://github.com/w3c-ccg/did-spec/issues/217, https://github.com/w3c-ccg/did-spec/issues/216, https://github.com/w3c-ccg/did-spec/issues/215, https://github.com/w3c-ccg/did-spec/issues/214.

In other cases where language doesn't read well, perhaps you could optionally also raise a PR and propose a better way to phrase it, e.g. https://github.com/w3c-ccg/did-spec/issues/220, https://github.com/w3c-ccg/did-spec/issues/211, https://github.com/w3c-ccg/did-spec/issues/212.

**Comment by mwherman2000** [comment]
I don't have time to invest creating PRs.  Find better writers.

**Comment by msporny** [comment]
> I don't have time to invest creating PRs. Find better writers.

@mwherman2000, you probably did not mean your response in the way it came across, but this is a good opportunity to point out that the CCG operates under the W3C "Code of Ethics and Professional Conduct". 

https://www.w3.org/Consortium/cepc/

We do so in order to ensure a positive workplace environment. 

Here is why your response is concerning:

Consensus is hard, specification editing is hard, @peacekeeper is volunteering his very valuable time to do both. He made a reasonable request, which would speed the rate at which your changes would make it into the specification. We are very busy as well.

> I don't have time to invest creating PRs.

That's unfortunate, and we'll try to make the changes you're requesting, but the way that you're going about your request is resulting in more work than necessary for us. We will have to triage your issue, process your issue, raise a PR, check to see if you agree with it, possibly have CG discussion around it, and then merge it. So, by not investing in creating your own PR, you're requiring multiple editors and the CCG to address your issue (which we can do and will do in time). Your response comes across as flippant and disrespectful to the time that others are putting in to process your issue.

> Find better writers.

This is also not respectful of the time that others have put into writing the specification. Yes, we all acknowledge that the specification needs work, and are striving to make it better. You are effectively communicating that 1) the writers are not competent, and 2) you don't have time to help the writers.

In the meantime, the writers will continue to improve the specification, we'll get to your issues eventually, but the more issues you raise, the longer it will take for us to process them vs. suggesting direct fixes to the specification text and reducing the time it takes for us to process your suggestions.

**Comment by mwherman2000** [comment]
@msporny I have invested literally man-months of effort providing feedback on the did-spec since November 2018. I have no apologies for not being able to provide more effort than I have. This project does need better writers so as to not impose wasteful and unnecessary work on the rest of the community. That's my point of view as a professional in this community.

With respect to the Code, perhaps you need to review your own comments: https://hyperonomy.com/2019/04/09/clique-speak/

**Comment by TallTed** [comment]
The sentence in question now reads --
`In cases where the <a>DID Registry</a>
is a distributed ledger, each entity may serve as its own root authority
&mdash; an architecture referred to as 
<a href="https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust/blob/master/final-documents/dpki.pdf">DPKI
(decentralized PKI)</a>.`
-- and surrounding text provides more clarity about other scenarios.

@mwherman2000 - Would you say this (#219) can be closed?

**Comment by mwherman2000** [comment]
@tallted Yes
