### ISSUE TITLE
[Question] DateTime vs Millisecond Timestamp

### ISSUE THREAD

**Issue by mehranshakeri** [w3c-ccg/did-spec#275]
Could you please explain why timestamp values are set as formatted DateTime instead of something like Unix Epochs?  e.g. [Created](https://w3c-ccg.github.io/did-spec/#created-optional) property. Is there any pros except human-readability?
My assumption is that DIDs will be used mainly by machines and my experience is having a Long value is much more developer friendly than a formatted String.

**Comment by dlongley** [comment]
@mehranshakeri,

There are a number of considerations that support using a formatted DateTime rather than a UNIX timestamp. These include at least:

1. JSON parsing issues with large numbers
2. Year 2038 issues with UNIX timestamps
3. [Priority of Constituencies](https://www.w3.org/TR/html-design-principles/#priority-of-constituencies)

We can avoid the first two problems entirely by using a standard string representation of a date, and since this is not that difficult to do for developers, it makes a lot of sense given issue 3. Developers/DID ledgers/networks/etc. can, of course, represent values in any preferred lossless way internally; the formatted date string is only for the standard representation.

**Comment by mehranshakeri** [comment]
@dlongley Thank you for quick and detailed reply :)
