### ISSUE TITLE
Into the Hands of Users

### ISSUE THREAD

**Issue by rschulman** [w3c-ccg/did-spec#57]
I recognize this is premature at this stage, but I wonder if anyone is talking about how we will start getting DID's into people's lives? Both as a thing that they possess (and understand) but also as a thing that is used. I'm very interested and passionate about self-sovereign identity, but conversations with my wife have shown that I'm not great at describing its importance. :) 

I'd love to join up with anyone else thinking about the problem.

**Comment by msporny** [comment]
> I recognize this is premature at this stage, but I wonder if anyone is talking about how we will start getting DID's into people's lives?

Yes, this was a topic of great discussion during this week at Rebooting the Web of Trust 6. Expect topic papers to come out talking about this after this week:

https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-spring2018/tree/master/draft-documents

**Comment by msporny** [comment]
The primer documents may also be helpful to you here, @rschulman:

https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-spring2018/tree/master/topics-and-advance-readings

I'm closing this issue as there is nothing to do wrt. the DID Specification. This issue is about supporting documentation and thinking, which is out of scope for the DID Spec.
